#General Settings
title: Hake Blog
subtitle: The personal blog of Sam Scott-Hake
email: sam_hake@live.co.uk

#Nav bar and links
nav:
- {name: Home, url: /}
- {name: About, url: /about}
- {name: Projects, url: /projects}
- {name: Blog, url: /blog}

#Projects
projects:
- {title: Orthographic camera, date: 26/06/15, url: /projects/ortho-camera, blurb: 'Using camera modes in threejs'}
- {title: Shapes and camera testing, date: 25/06/26, url: /projects/shape-test, blurb: 'Testing shapes and cameras in Three.js.'}
- {title: Threejs, date: 22/6/15, url: /projects/threejs, blurb: 'An animated ball and cube.'}
- {title: Hypnotiser, date: 20/6/15, url: /projects/hypnotiser, blurb: 'An odd Dr Who inspired animation.'}
- {title: Tumbling Shapes, date: 11/06/15, url: /projects/tumbling-shapes, blurb: 'Tumbling shapes in ThreeJS.'}
- {title: Painter - WIP, date: 10/06/15, url: /projects/painter, blurb: 'Paint app with color and size options.'}
- {title: Spirograph, date: 03/06/15, url: /projects/spirograph, blurb: 'Spinning orbs leaving trails.'}
- {title: Seenit Angular, date: 29/05/15, url: /projects/seenit-angular}
- {title: Shoal, date: 26/05/15, url: /projects/shoal}
- {title: Coloured Fireflies, date: 25/05/15, url: /projects/coloured-fireflies}
- {title: Coloured Liquid, date: 25/05/15, url: /projects/coloured-liquid}
- {title: jQuery DOM Paractice, date: 23/05/15, url: /projects/dom-traversal}
- {title: Music Player, date: 20/05/15, url: /projects/music-player}
- {title: Angular Store, date: 19/05/15, url: /projects/angular-store}
- {title: Twilight, date: 25/04/15, url: /projects/twilight}
- {title: Angular Test, date: 24/04/15, url: /projects/angular-test}
- {title: Particles Test, date: 23/04/15, url: /projects/particles-test}
- {title: Cavcas Clock, date: 23/04/15, url: /projects/canvas-clock}
- {title: Snake, date: 21/04/15, url: /projects/snake}
- {title: Throwing Squares, date: 20/04/15, url: /projects/throwing-squares}
- {title: Blinking Squares, date: 17/04/15, url: /projects/blinking-squares}
- {title: Colour Clock, date: 16/04/15, url: /projects/colour-clock}
- {title: Birthday Facts, date: 14/04/15, url: /projects/birthday-facts}
- {title: Animator, date: 10/04/15, url: /projects/animator}
- {title: Day Counter, date: 09/04/15, url: /projects/day-counter}
- {title: Squares, date: 08/04/15, url: /projects/squares}
